tango_with_django_project/rango/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name='rango'
urlpatterns = [
	path('', views.index, name='index'),
	path('about/', views.about, name='about'),
  path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
  path('add_category/', views.add_category, name='add_category'),
  path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
  path('register/', views.register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('rango/', include('rango.urls'))
]

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
  name = models.CharField(max_length=128, unique=True)
  views = models.IntegerField(default=0)
  likes = models.IntegerField(default=0)
  slug = models.SlugField(unique=True)

  def save(self, *args, **kwargs):
    self.slug = slugify(self.name)
    super(Category, self).save(*args, **kwargs)

  class Meta:
    verbose_name_plural = 'Categories'
  
  def __str__(self):
    return self.name

class Page(models.Model):
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  title = models.CharField(max_length=128)
  url = models.URLField()
  views = models.IntegerField(default=0)
      
  def __str__(self):
    return self.title

class UserProfile(models.Model):
  # link UserProfile to User model instance
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  # additional attrs
  website = models.URLField(blank=True)
  picture = models.ImageField(upload_to='profile_images', blank=True)

  def __str__(self):
    return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
  name = forms.CharField(help_text='Category Name')
  # name = forms.CharField(max_length=128, help_text='Category Name')
  # views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  # likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  # slug = forms.CharField(widget=forms.HiddenInput(), required=False)

  class Meta:
    model = Category
    fields = ('name',)

class PageForm(forms.ModelForm):
  title = forms.CharField(max_length=128,  help_text='Page Title')
  url = forms.URLField(max_length=200, help_text='Page URL')
  views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

  def clean(self):
    cleaned_data = self.cleaned_data
    url = cleaned_data.get('url')

    if url and not url.startswith('http://'):
      url = 'http://' + url
      cleaned_data['url'] = url
      return cleaned_data

  class Meta:
    model = Page
    exclude = ('category',)

class UserForm(forms.ModelForm):
  password = forms.CharField(widget=forms.PasswordInput())

  class Meta:
    model = User
    fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
  class Meta:
    model = UserProfile
    fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category, Page
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login

def index(request):
  category_list = Category.objects.order_by('-likes')[:5]
  page_list = Page.objects.order_by('-views')[:5]
  context_dict = {'categories': category_list, 'pages': page_list}
  return render(request, 'rango/index.html', context_dict)

def about(request):
  print(request.method)
  print(request.user)
  return render(request, 'rango/about.html')

def show_category(request, category_name_slug):
  context_dict = {}

  try:
    category = Category.objects.get(slug=category_name_slug)

    pages = Page.objects.filter(category=category)

    context_dict['pages'] = pages

    context_dict['category'] = category

  except Category.DoesNotExist:
    context_dict['category'] = None
    context_dict['pages'] = None

  return render(request, 'rango/category.html', context_dict)

def add_category(request):
  form = CategoryForm()

  if request.method == "POST":
    form = CategoryForm(request.POST)
    if form.is_valid():
      form.save(commit=True)

      return redirect('index')
    else:
      print(form.errors)

  return render(request, 'rango/add_category.html', {'form':form})

def add_page(request, category_name_slug):

  try:
    category = Category.objects.get(slug=category_name_slug)
  except Category.DoesNotExist:
    # category = None
    return redirect('index')

  form = PageForm()

  if request.method == 'POST':
    form = PageForm(request.POST)
    if form.is_valid():
      if category:
        page = form.save(commit=False)
        page.category = category
        page.views = 0
        page.save()
        # return show_category(request, category_name_slug)
        return HttpResponseRedirect(reverse('rango:show_category', args=(category_name_slug,)))

    else:
      print(form.errors)
  context_dict = {'form': form, 'category': category}
  return render(request, 'rango/add_page.html', context_dict)

def register(request):
  registered = False

  if request.method == 'POST':
    user_form = UserForm(data=request.POST)
    profile_form = UserProfileForm(data=request.POST)

    if user_form.is_valid() and profile_form.is_valid():
      user = user_form.save()
      user.set_password(user.password)
      user.save()

      profile = profile_form.save(commit=False)
      profile.user = user

      if 'picture' in request.FILES:
        profile.picture = request.FILES['picture']

      profile.save()

      registered = True
      return render(request, 'rango/register.html', {'registered': registered})
    else:
      print(user_form.errors, profile_form.errors)
  else:
    user_form = UserForm()
    profile_form = UserProfileForm()

    return render(request, 'rango/register.html',{'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')

    # authenticate() returns User Object or None
    user = authenticate(username=username, password=password)

    if user:
      if user.is_active():
        login(request, user)
        return HttpResponseRedirect(reverse('index'))
      else:
        return HttpResponse('Your rango account is disabled')
    else:
      # print("Invalid login details")
      return HttpResponse('Invalid login details')
  else:
    return render(request, 'rango/login.html')

tango_with_django_project/rango/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
 	<title>Rango</title>
 	<meta charset="utf-8" />
 	{% load staticfiles %}
  {% load rango_template_tags %}
  	<!-- <link rel="shortcut icon" href="{% static 'info/img/textcube.png' %}"> -->

 	<meta name="viewport" content = "width=device-width, initial-scale=1">

 	<!-- General Style Sheets -->
 	<link rel="stylesheet" href="{% static 'rango/css/bootstrap.min.css' %}"/>
 	<link rel="stylesheet" href="{% static 'rango/css/cus.css' %}"/>

 	<!-- JS for collapsible navbar -->
 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <a class="navbar-brand">Rango</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button> 
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right" style="padding-right: 30px;">
        <li><a href="{% url 'rango:add_category' %}"> Add New Category</a></li>
        <li><a href="{% url 'rango:about' %}"> About</a></li>
        <li><a href="{% url 'rango:index' %}"> Index</a></li>
      </ul>
    </div>
  </nav>
  <div>
    {% block sidebar_block %}
      {% get_category_list category %}
    {% endblock %}
  </div>
  
  {% block title_block %}
  {% endblock %}

  {% block content %}
  {% endblock %}
  <br><hr>
</body>

</html>
 

tango_with_django_project/rango/templates/rango/about.html
{% extends 'base.html' %}
{% block content %}
<h1> Rango says here is the about page. </h1>
<button><a href="{% url 'rango:index' %}"> back </a></button>
{% endblock %}
 

tango_with_django_project/rango/templates/rango/add_category.html
{% extends 'base.html' %}
{% block content %}
<h1> Add a category </h1>
<form id='category_form' method='post' action="{% url 'rango:add_category'%}">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}
  {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
  {% endfor %}
  <input type='submit' name='submit' value='Create'/>
</form>
{% endblock %}

tango_with_django_project/rango/templates/rango/add_page.html
{% extends 'base.html' %}
{% block content %}
<h1> Add a Page for {{category}}</h1>
<form id='page_form' method='post' action="{% url 'rango:add_page' category.slug %}">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}
  {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
  {% endfor %}
  <input type='submit' name='submit' value='Create page'/>
</form>
{% endblock %}

tango_with_django_project/rango/templates/rango/category.html
{% extends 'base.html' %}
{% block content %}
<div>
  {% if category %}
    <a href="{% url 'rango:add_page' category.slug %}"> add page </a>
    <h1> {{ category.name }} </h1>
    {% if pages %}
      <ul>
      {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <strong> No pages currently available </strong>
    {% endif %}
  {% else %}
    The specified category DNE!
  {% endif %}
</div>



{% endblock%}

tango_with_django_project/rango/templates/rango/cats.html
<ul>
  {% if cats %}
    {% for c in cats %}
      {% if c == act_cat %}
        <li>
        <strong>
          <a href="{% url 'rango:show_category' c.slug %}">{{c.name}}</a>
        </strong>
        </li>
      {% else %}
        <li>
          <a href="{% url 'rango:show_category' c.slug %}">{{c.name}}</a>
        </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <li><strong>There are no categories present.</strong></li>
  {% endif %}
</ul>

tango_with_django_project/rango/templates/rango/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
  <div class='row'>
    <h1 style="text-align: center;"> Index </h1>
    <div class="col-md-4 col-md-offset-2">
      {% if categories %}
      <h1> Top 5 Categories </h1>
      <ul>
        {% for category in categories %}
        <li> 
          <a href='{% url "rango:show_category" category.slug %}'>{{ category.name }}</a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
        <strong> No categories at the moment </strong>
      {% endif %}
    </div>
    <div class="col-md-4 col-md-offset-2">
      {% if pages %}
      <h1> Most liked Pages </h1>
      <ul>
        {% for page in pages %}
        <li> 
          <a href='{{ page.url }}'>{{ page.title }}</a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
        <strong> No pages at the moment </strong>
      {% endif %}
    </div>
    <img src='{{ MEDIA_URL}}eversince.jpg' style="width: 250px;}" />
  </div>
</div>
{% endblock %}

tango_with_django_project/rango/templates/rango/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}
  <h1>Register</h1>
{% endblock %}

{% block content %}
  {% if registered %}
    Rango says: <strong> thank you for registering!</strong>
    <a href="{% url 'rango:index' %}">Return to the homepage </a><br/>
  {% else %}
    Rango says: <strong> register here! </strong><br/>
    <form id='user_form' method='post' action="{% url 'rango:register' %}" enctype='multipart/form-data'>
      {% csrf_token %}

      {{user_form.as_p}}
      {{profile_form.as_p}}

      <input type='submit' name='submit' value='Register'/>
    </form>
  {% endif %}
{% endblock %}